version: '3.8'

services:
  app:
    pull_policy: build
    # restart: "always"
    build: .
    environment:
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      DISCORD_CLIENT_ID: "${DISCORD_CLIENT_ID}"
      DISCORD_CLIENT_SECRET: "${DISCORD_CLIENT_SECRET}"
      DISCORD_GUILD_ID: "${DISCORD_GUILD_ID}"
      DISCORD_QA_ROLES: "${DISCORD_QA_ROLES}"
      CF_SECURITY_TOKEN: "${CF_SECURITY_TOKEN}"
      HTTP_HOST: "${HTTP_HOST}"
      HTTP_PORT: "${HTTP_PORT}"
    networks:
      qa-auth:
        ipv4_address: 172.32.0.3

networks:
  qa-auth:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.32.0.0/16"